=== yunii25/Project_WebDev2/xmlfiles/hotel_room.dtd
<!ELEMENT rooms (room+)>
<!ELEMENT room (roomId,room_description,price,media)>
<!ELEMENT roomId (#PCDATA)>
<!ELEMENT room_description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT media (#PCDATA)>

<!ATTLIST room category CDATA #REQUIRED>
<!ATTLIST media type CDATA #IMPLIED>

=== yunii25/Project_WebDev2/xmlfiles/room.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rooms SYSTEM "hotel_room.dtd">
<rooms><room category="Excecutive Suite"><roomId>1</roomId><room_description>Experience the pinnacle of luxury and comfort in our executive room, where elegance meets modern amenities to create a truly exceptional stay.</room_description><price>50000.00</price><media type="image">executive.jpg</media></room><room category="Premiere Suite"><roomId>2</roomId><room_description>Indulge in the epitome of luxury and sophistication in our premiere room, where lavish furnishings and exquisite design combine to offer an unforgettable experience.</room_description><price>39000.99</price><media type="image">premiere.jpg</media></room><room category="El Hotel Suite"><roomId>3</roomId><room_description>Escape to El Hotel and discover a world of elegance and refinement, where impeccable service, stunning decor, and luxurious amenities come together to create an unforgettable stay.</room_description><price>29000.99</price><media type="image">el_hotel.jpg</media></room><room category="Single Bed"><roomId>4</roomId><room_description>DesertsRelax and unwind in our cozy single bed room, featuring a comfortable bed, soothing ambiance, and all the essentials for a peaceful nights rest.</room_description><price>19000.99</price><media type="image">single.jpg</media></room></rooms>
